#!/usr/bin/env bash
# Test suite for scripts/tools/classify-files.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
TOOL="$ROOT_DIR/scripts/tools/classify-files.sh"

source "$SCRIPT_DIR/test-helpers.sh"

echo "=== classify-files.sh tests ==="
echo ""

FIXTURE="$(mktemp -d)"
trap 'rm -rf "$FIXTURE"' EXIT

# Seed a fixture repo-shaped tree.
mkdir -p "$FIXTURE/src/api" "$FIXTURE/tests" "$FIXTURE/generated"
cat >"$FIXTURE/src/api/handler.py" <<'EOF'
def handle(req):
    return 200
EOF
cat >"$FIXTURE/tests/test_handler.py" <<'EOF'
def test_handler():
    assert True
EOF
cat >"$FIXTURE/generated/schema.py" <<'EOF'
# Code generated by codegen.py DO NOT EDIT.
SCHEMA = {}
EOF
cat >"$FIXTURE/README.md" <<'EOF'
# Fixture
EOF

jsonl_out="$("$TOOL" --root "$FIXTURE")"

# --- Each emitted line parses as JSON ---
ALL_JSON=true
while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    if command -v jq >/dev/null 2>&1; then
        echo "$line" | jq . >/dev/null 2>&1 || ALL_JSON=false
    elif command -v python3 >/dev/null 2>&1; then
        echo "$line" | python3 -c 'import json,sys; json.load(sys.stdin)' 2>/dev/null || ALL_JSON=false
    fi
done <<<"$jsonl_out"
assert "Every output line is valid JSON" "$ALL_JSON"

# --- Source files classified as 'source' ---
if echo "$jsonl_out" | grep -qE '"path":"src/api/handler.py".*"category":"source".*"is_test":false'; then
    assert "Source file classified as source, not test" "true"
else
    assert "Source file classified as source, not test" "false"
fi

# --- Test files classified as test ---
if echo "$jsonl_out" | grep -qE '"path":"tests/test_handler.py".*"category":"test".*"is_test":true'; then
    assert "test_*.py flagged as test" "true"
else
    assert "test_*.py flagged as test" "false"
fi

# --- Generated files flagged ---
if echo "$jsonl_out" | grep -qE '"path":"generated/schema.py".*"is_generated":true'; then
    assert "Generated file flagged" "true"
else
    assert "Generated file flagged" "false"
fi

# --- Language inference ---
if echo "$jsonl_out" | grep -qE '"path":"src/api/handler.py","lang":"python"'; then
    assert "Python language inferred" "true"
else
    assert "Python language inferred" "false"
fi

if echo "$jsonl_out" | grep -qE '"path":"README.md","lang":"markdown"'; then
    assert "Markdown language inferred" "true"
else
    assert "Markdown language inferred" "false"
fi

# --- --json emits a valid JSON array ---
json_arr="$("$TOOL" --root "$FIXTURE" --json)"
if command -v jq >/dev/null 2>&1; then
    if echo "$json_arr" | jq 'length' >/dev/null 2>&1; then
        assert "--json emits a valid JSON array" "true"
    else
        assert "--json emits a valid JSON array" "false"
    fi
fi

# --- Module attribution uses first path segment ---
if echo "$jsonl_out" | grep -qE '"path":"src/api/handler.py".*"module":"src"'; then
    assert "Module = first path segment (src)" "true"
else
    assert "Module = first path segment (src)" "false"
fi

echo ""
echo "=== Results: $PASS passed, $FAIL failed ==="
exit "$FAIL"
