/**
 * DRAFT AUDIO PLAYER
 * Logic for playing local audio files generated by NotebookLM.
 */

class DraftAudioPlayer {
    constructor() {
        this.audio = new Audio();
        this.isPlaying = false;
        this.currentChapterId = '';
        this.chapters = []; // Set by page: [{id, title}]
        this.currentIdx = -1;

        this.initUI();
        this.attachListeners();
    }

    initUI() {
        const playerHtml = `
            <div class="draft-audio-player" id="draft-audio-player">
                <div class="audio-player-timeline" id="audio-timeline"><div class="audio-player-progress" id="audio-progress"></div></div>
                <div class="audio-player-info">
                    <div class="audio-player-cover">
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M12 1a2 2 0 0 1 2 2v10a2 2 0 0 1-4 0V3a2 2 0 0 1 2-2z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg>
                    </div>
                    <div class="audio-player-text">
                        <span class="audio-player-title" id="audio-title">Not Playing</span>
                        <span class="audio-player-subtitle" id="audio-subtitle">Select a chapter</span>
                    </div>
                </div>
                <div class="audio-player-controls">
                    <button class="ctrl-btn" id="audio-prev"><svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M6 6h2v12H6zm3.5 6L18 18V6z"/></svg></button>
                    <button class="ctrl-btn ctrl-btn-main" id="audio-play-pause">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" id="play-icon"><path d="M8 5v14l11-7z"/></svg>
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" id="pause-icon" style="display:none;"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>
                    </button>
                    <button class="ctrl-btn" id="audio-next"><svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"/></svg></button>
                </div>
                <div class="audio-player-settings">
                    <button class="ctrl-btn" id="audio-stop"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/></svg></button>
                </div>
            </div>
        `;
        document.body.insertAdjacentHTML('beforeend', playerHtml);

        this.el = document.getElementById('draft-audio-player');
        this.playBtn = document.getElementById('audio-play-pause');
        this.playIcon = document.getElementById('play-icon');
        this.pauseIcon = document.getElementById('pause-icon');
        this.progressEl = document.getElementById('audio-progress');
        this.timelineEl = document.getElementById('audio-timeline');
        this.titleEl = document.getElementById('audio-title');
        this.subtitleEl = document.getElementById('audio-subtitle');
    }

    attachListeners() {
        this.playBtn.onclick = () => this.togglePlayback();
        document.getElementById('audio-stop').onclick = () => this.stop();
        document.getElementById('audio-prev').onclick = () => this.navigate(-1);
        document.getElementById('audio-next').onclick = () => this.navigate(1);

        // Timeline seek
        this.timelineEl.onclick = (e) => {
            if (!this.audio.duration) return;
            const rect = this.timelineEl.getBoundingClientRect();
            const pct = (e.clientX - rect.left) / rect.width;
            this.audio.currentTime = pct * this.audio.duration;
        };

        this.audio.ontimeupdate = () => {
            if (!this.audio.duration) return;
            const pct = (this.audio.currentTime / this.audio.duration) * 100;
            this.progressEl.style.width = `${pct}%`;
        };

        this.audio.onended = () => this.navigate(1);

        this.audio.onerror = () => {
            if (this.currentIdx !== -1) {
                this.titleEl.innerText = 'File not found';
                this.subtitleEl.innerText = `chapter-${this.currentIdx}.m4a missing`;
                this.isPlaying = false;
                this.updateIcons();
            }
        };

        document.addEventListener('click', (e) => {
            const btn = e.target.closest('.btn-listen-chapter');
            if (btn) {
                window.location.href = (document.body.dataset.chapter ? '../' : './') + 'audio/';
            }
        });
    }

    /** Set the chapter list so navigate() works. Called by the page. */
    setChapters(chapters) {
        this.chapters = chapters;
    }

    playTrack(index, title, subtitle) {
        this.currentIdx = index;

        const isAudioPage = document.body.classList.contains('audio-player-page');
        const baseUrl = isAudioPage ? './audio-files/' : '../audio/audio-files/';

        this.audio.src = `${baseUrl}chapter-${index}.m4a`;
        this.titleEl.innerText = title;
        this.subtitleEl.innerText = subtitle || 'Draft Audiobook';

        this.el.classList.add('visible');
        this.audio.play().then(() => {
            this.isPlaying = true;
            this.updateIcons();
        }).catch(() => {
            // Autoplay blocked — show play button so user can tap
            this.isPlaying = false;
            this.updateIcons();
        });

        // Highlight active playlist item
        document.querySelectorAll('.playlist-item').forEach((el, i) => {
            el.classList.toggle('active', i === index);
        });
    }

    togglePlayback() {
        if (!this.audio.src) return;
        if (this.isPlaying) {
            this.audio.pause();
            this.isPlaying = false;
        } else {
            this.audio.play().then(() => {
                this.isPlaying = true;
                this.updateIcons();
            }).catch(() => {});
        }
        this.updateIcons();
    }

    stop() {
        this.audio.pause();
        this.audio.currentTime = 0;
        this.isPlaying = false;
        this.el.classList.remove('visible');
        this.updateIcons();
        document.querySelectorAll('.playlist-item.active').forEach(el => el.classList.remove('active'));
    }

    navigate(dir) {
        if (this.chapters.length === 0) return;
        const next = this.currentIdx + dir;
        if (next < 0 || next >= this.chapters.length) return;
        const ch = this.chapters[next];
        this.playTrack(next, ch.title, 'Draft Audiobook');
    }

    updateIcons() {
        this.playIcon.style.display = this.isPlaying ? 'none' : 'block';
        this.pauseIcon.style.display = this.isPlaying ? 'block' : 'none';
    }
}

window.addEventListener('DOMContentLoaded', () => {
    window.draftAudio = new DraftAudioPlayer();
});
