#!/usr/bin/env bash
# classify-files.sh — deterministic file classification for a repo.
#
# Walks --root (default: cwd) respecting common ignore globs, emits one JSON
# object per line (JSONL) with language, category, test/generated flags,
# LOC, and top-level module.
#
# Usage:
#   scripts/tools/classify-files.sh [--root DIR] [--json]
#
# Output fields: path, lang, category, is_test, is_generated, loc, module
# Exit codes: 0 OK (with or without results), 1 invocation error.
set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

ROOT="."
FORMAT="jsonl"

usage() {
    cat <<'EOF'
classify-files.sh — deterministic file classification (JSONL).

Usage:
  scripts/tools/classify-files.sh [--root DIR] [--json]

Flags:
  --root DIR    Root directory to scan (default: cwd).
  --json        Emit a single JSON array instead of JSONL.
  --help        Show this help.

Output (per file): {path, lang, category, is_test, is_generated, loc, module}

Language is inferred from extension and shebang. A file is classified as a
test when its path or basename matches common test patterns. It is flagged
generated when the first 5 lines contain "Code generated" or "DO NOT EDIT".
Module is the first path segment under root.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root) ROOT="$2"; shift 2;;
        --json) FORMAT="json"; shift;;
        --jsonl) FORMAT="jsonl"; shift;;
        --help|-h) usage; exit 0;;
        *) echo "Unknown flag: $1" >&2; usage >&2; exit 1;;
    esac
done

if [[ ! -d "$ROOT" ]]; then
    echo "ERROR: --root '$ROOT' is not a directory" >&2
    exit 1
fi

# Exclusions: common generated/vendor directories.
EXCLUDE_DIRS=(
    .git node_modules dist build out .next .venv venv __pycache__
    target vendor third_party .mypy_cache .pytest_cache coverage
    .cache .tox .gradle .idea .vscode
    .terraform _build .svelte-kit .dart_tool Pods cdk.out
    .turbo .parcel-cache .nuxt .vercel .pnpm-store
)

lang_for() {
    local path="$1"
    local base="$(basename "$path")"
    local ext="${base##*.}"
    [[ "$ext" == "$base" ]] && ext=""

    case "$ext" in
        py) echo "python";;
        js|mjs|cjs) echo "javascript";;
        ts|tsx) echo "typescript";;
        jsx) echo "javascript";;
        go) echo "go";;
        rs) echo "rust";;
        java) echo "java";;
        kt|kts) echo "kotlin";;
        c|h) echo "c";;
        cc|cpp|cxx|hpp|hh|hxx) echo "cpp";;
        rb) echo "ruby";;
        sh|bash) echo "bash";;
        md|markdown) echo "markdown";;
        yml|yaml) echo "yaml";;
        json) echo "json";;
        toml) echo "toml";;
        proto) echo "proto";;
        sql) echo "sql";;
        html|htm) echo "html";;
        css) echo "css";;
        scss|sass) echo "sass";;
        lua) echo "lua";;
        php) echo "php";;
        cs) echo "csharp";;
        swift) echo "swift";;
        *)
            # shebang-based detection for extensionless scripts
            if [[ -f "$path" ]] && head -1 "$path" 2>/dev/null | grep -qE '^#!'; then
                local shebang
                shebang="$(head -1 "$path")"
                case "$shebang" in
                    *bash*|*zsh*|*/sh*) echo "bash";;
                    *python*) echo "python";;
                    *node*) echo "javascript";;
                    *ruby*) echo "ruby";;
                    *) echo "other";;
                esac
            else
                echo "other"
            fi
            ;;
    esac
}

is_test_file() {
    local path="$1"
    local base="$(basename "$path")"

    # Path segment
    case "/$path/" in
        */tests/*|*/test/*|*/__tests__/*|*/spec/*|*/specs/*) echo "true"; return;;
    esac

    # Filename patterns
    case "$base" in
        test_*.py|*_test.py|tests.py|conftest.py) echo "true"; return;;
        *_test.go) echo "true"; return;;
        *.test.ts|*.test.tsx|*.test.js|*.test.jsx) echo "true"; return;;
        *.spec.ts|*.spec.tsx|*.spec.js|*.spec.jsx) echo "true"; return;;
        *Test.java|*Tests.java|*Spec.java) echo "true"; return;;
        test-*.sh|*-test.sh|*_test.sh) echo "true"; return;;
    esac

    echo "false"
}

is_generated() {
    local path="$1"
    [[ -f "$path" ]] || { echo "false"; return; }
    if head -5 "$path" 2>/dev/null | grep -qE 'Code generated|DO NOT EDIT|@generated|autogenerated'; then
        echo "true"
    else
        echo "false"
    fi
}

module_for() {
    local rel="$1"
    local first="${rel%%/*}"
    if [[ "$first" == "$rel" ]]; then
        echo "."
    else
        echo "$first"
    fi
}

# Build find with prunes for excluded dirs. Use absolute root so emitted paths are absolute.
ROOT_REAL="$(cd "$ROOT" && pwd)"
FIND_ARGS=("$ROOT_REAL" -type d \( )
first_dir=true
for dir in "${EXCLUDE_DIRS[@]}"; do
    if $first_dir; then
        FIND_ARGS+=(-name "$dir")
        first_dir=false
    else
        FIND_ARGS+=(-o -name "$dir")
    fi
done
FIND_ARGS+=(\) -prune -o -type f -print)

first_record=true

emit_record() {
    local json="$1"
    if [[ "$FORMAT" == "json" ]]; then
        if $first_record; then
            printf '[\n  %s' "$json"
            first_record=false
        else
            printf ',\n  %s' "$json"
        fi
    else
        printf '%s\n' "$json"
    fi
}

while IFS= read -r file; do
    # `find -type f` guarantees the entry is a regular file; no re-check needed.
    # `find` run on an absolute ROOT emits absolute paths — strip the prefix.
    rel="${file#"$ROOT_REAL/"}"
    case "$rel" in
        .git/*) continue;;
    esac

    lang="$(lang_for "$file")"
    is_test="$(is_test_file "$rel")"
    gen="$(is_generated "$file")"
    module="$(module_for "$rel")"

    loc="$(wc -l <"$file" 2>/dev/null | tr -d ' ' || echo 0)"

    # Category: test > generated > source > config/docs
    if [[ "$is_test" == "true" ]]; then
        category="test"
    elif [[ "$gen" == "true" ]]; then
        category="generated"
    else
        case "$lang" in
            markdown|yaml|json|toml) category="docs";;
            *) category="source";;
        esac
    fi

    record=$(printf '{"path":"%s","lang":"%s","category":"%s","is_test":%s,"is_generated":%s,"loc":%s,"module":"%s"}' \
        "$(json_escape "$rel")" \
        "$(json_escape "$lang")" \
        "$(json_escape "$category")" \
        "$is_test" \
        "$gen" \
        "$loc" \
        "$(json_escape "$module")")
    emit_record "$record"
done < <(find "${FIND_ARGS[@]}" 2>/dev/null | sort)

if [[ "$FORMAT" == "json" ]]; then
    if $first_record; then
        printf '[]\n'
    else
        printf '\n]\n'
    fi
fi
