#!/usr/bin/env bash
# graph-snapshot.sh — materialize a lightweight, committed knowledge-graph snapshot.
#
# In the codebase-memory-mcp model, Claude Code skills query the engine live
# (on-demand indexing into ~/.cache). This snapshot exists for the two cases
# that cannot run the engine: PR-reviewable graph state, and the Copilot/Gemini
# integrations (which read committed files, not MCP). It is small and derived —
# git remains the source of truth.
#
# Writes under <repo>/draft/graph/:
#   schema.yaml          engine + project metadata + counts (gates skill graph use)
#   architecture.json    raw get_architecture(all) output
#   hotspots.jsonl       fan-in-ranked symbols, one JSON object per line
#   module-deps.mermaid  co-change coupling diagram
#   proto-map.mermaid    detected-route diagram
#   okf/                 Open Knowledge Format bundle (portable markdown mirror)
#
# Usage: scripts/tools/graph-snapshot.sh [--repo DIR] [--out DIR]
# Exit codes: 0 OK, 1 invocation error, 2 graph engine unavailable.
set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$TOOLS_DIR/_lib.sh"

REPO="."
OUT_DIR=""

usage() {
    cat <<'EOF'
graph-snapshot.sh — write a committed knowledge-graph snapshot to draft/graph/.

Usage:
  scripts/tools/graph-snapshot.sh [--repo DIR] [--out DIR]

Flags:
  --repo DIR  Repository root (default: cwd).
  --out DIR   Snapshot dir (default: <repo>/draft/graph).
  --help      Show this help.

Exit 0 on success, 2 when the graph engine is unavailable (no snapshot written).
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo) REPO="$2"; shift 2;;
        --out) OUT_DIR="$2"; shift 2;;
        --help|-h) usage; exit 0;;
        *) echo "Unknown flag: $1" >&2; usage >&2; exit 1;;
    esac
done

[[ -d "$REPO" ]] || { echo "ERROR: --repo '$REPO' is not a directory" >&2; exit 1; }

REPO_ABS="$(cd "$REPO" && pwd)"
SELF_REPO="$(cd "$TOOLS_DIR/../.." && pwd)"
OUT="${OUT_DIR:-$REPO_ABS/draft/graph}"

find_memory_bin "$REPO_ABS" "$SELF_REPO" || { echo "graph engine unavailable — no snapshot written" >&2; exit 2; }
command -v jq >/dev/null 2>&1 || { echo "jq required for snapshot" >&2; exit 2; }

PROJECT="$(memory_ensure_index "$REPO_ABS" || true)"
[[ -n "$PROJECT" ]] || { echo "could not index repo — no snapshot written" >&2; exit 2; }

mkdir -p "$OUT"

# 1. architecture.json (full get_architecture)
ARCH="$(memory_cli get_architecture "{\"project\":\"$PROJECT\",\"aspects\":[\"all\"]}" || echo '{}')"
echo "$ARCH" | jq '.' > "$OUT/architecture.json"

# 2. hotspots.jsonl (one object per line)
"$TOOLS_DIR/hotspot-rank.sh" --repo "$REPO_ABS" 2>/dev/null \
    | jq -c '.hotspots[]?' > "$OUT/hotspots.jsonl" || true

# 3. mermaid diagrams (best-effort; tools emit a stub + exit 2 if empty)
"$TOOLS_DIR/mermaid-from-graph.sh" --repo "$REPO_ABS" --diagram module-deps > "$OUT/module-deps.mermaid" 2>/dev/null || true
"$TOOLS_DIR/mermaid-from-graph.sh" --repo "$REPO_ABS" --diagram proto-map  > "$OUT/proto-map.mermaid"  2>/dev/null || true

# 4. OKF bundle (best-effort) — portable Open Knowledge Format mirror of the graph.
"$TOOLS_DIR/okf-emit.sh" --repo "$REPO_ABS" --snapshot "$OUT" --out "$OUT/okf" >/dev/null 2>&1 || true

# 5. schema.yaml — metadata + gate for skill graph use
NODES="$(echo "$ARCH" | jq -r '.total_nodes // 0')"
EDGES="$(echo "$ARCH" | jq -r '.total_edges // 0')"
HOTN="$(wc -l < "$OUT/hotspots.jsonl" | tr -d ' ')"
VER="$("$MEMORY_BIN" --version 2>/dev/null | awk '{print $NF}' || echo unknown)"
cat > "$OUT/schema.yaml" <<EOF
# Draft knowledge-graph snapshot — generated by scripts/tools/graph-snapshot.sh
# Derived from the codebase-memory-mcp engine; git remains source of truth.
engine: codebase-memory-mcp
engine_version: "$VER"
project: "$PROJECT"
generated_at: "$(date -Iseconds 2>/dev/null || date)"
nodes: $NODES
edges: $EDGES
hotspots: $HOTN
artifacts:
  - architecture.json
  - hotspots.jsonl
  - module-deps.mermaid
  - proto-map.mermaid
  - okf/
EOF

echo "Snapshot written to $OUT (nodes=$NODES edges=$EDGES hotspots=$HOTN)"
exit 0
